### ISSUE TITLE
No converter registered for type `paragraph`

### ISSUE THREAD

**Issue by wtoalabi** [MotivoZwolle/editorjs-data-converter#14]
Awesome tool!
Great job!
I just got into this and I have been impressed by the way the implementation was explained. Straightforward!
For context, I cam from here: https://github.com/codex-team/editor.js/issues/676
And I decided to take this for a spin.
Everything went well until I hit this snag: No converter registered for type `paragraph`
This was the data I sent to the server: 
`$data  = ["blocks" => [ [ "type" => "paragraph", "data"=> [ "text"=> "ededede" ]] ]];`
and called it like so: 
`resolve(DataConverter::class)->init(json_encode($data))`

I am sure there is something I am missing.
Your help is appreciated.

Thanks!

**Comment by wotta** [comment]
@wtoalabi thanks for your kind words. Could you share some details on your laravel version that you are using?

I will take a look at this issue in a 2 days since I am on vacation.

**Comment by wotta** [comment]
@wtoalabi sorry for the late response. My vacation was a bit heck tick so I didn't have the time to look at it.

I will take a look at this today and I hope I can help you resolve this.

**Comment by wotta** [comment]
@wtoalabi I tried reproducing the error that you got but I couldn't get the same error.

My decoded data structure looks like this:
```
[
     "time" => 1578291097261,
     "blocks" => [
       [
         "type" => "paragraph",
         "data" => [
           "text" => "Some content.",
         ],
       ],
     ],
     "version" => "2.15.1",
   ]
```

**Comment by wtoalabi** [comment]
Ha!
Wotta!!!

I am so sorry for getting back so late!!!!
Holidays and all.
I am grateful for taking this up and spending your time on this for me.
WOW!

Unfortunately I have since decided to use some other tools....
But I am so grateful for taking the time out of your busy schedule to attend to such a benign headache...So sorry for wasting your time.

Thanks so much!!!!

**Comment by wotta** [comment]
@wtoalabi no problem. Thanks for showing interest!
