### ISSUE TITLE
Support for Laravel 7x

### ISSUE THREAD

**Issue by snake-py** [MotivoZwolle/editorjs-data-converter#16]
When I am trying to install the package with composer I get:

```
$ composer require motivo/editorjs-data-converter
Using version ^1.0 for motivo/editorjs-data-converter
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

Problem 1
    - Conclusion: remove laravel/framework v7.2.2
    - Conclusion: don't install laravel/framework v7.2.2
```

**Comment by wotta** [comment]
Thanks for the issue, I will try to resolve this as soon as possible.
I will update you when a new version is available.

**Comment by wotta** [comment]
Hello @snake-py,

This issue should be resolved as of now.
This is fixed in PR #17.

Could you try and run `composer require motivo/editorjs-data-converter` again?

I will close it for now but if the fix didn't work for you please reply.

**Comment by snake-py** [comment]
Hello @wotta yes I could install it thank you for resolving it so fast. 

Could you perhaps further assist me? I have trouble referencing the correct class to use the default parser. 

I located it in my vendor folder 
![image](https://user-images.githubusercontent.com/59285387/80207996-92a39380-862f-11ea-98c0-0a6ecc706355.png)
but what reference do I need to use in my controller?
also, it would be great if you could add an example of the expected JSON data, since by default the editorjs data comes as nested json data where on the top level a timestamp ect. is saved.

**Comment by wotta** [comment]
Sure, so the readme states that you should call the following way to use the converter.

This might not be the best way but we are rethinking how to call this correctly so it feels normal in the Laravel way so to speak.

```php

$jsonContent = '{"time":1587728766281,"blocks":[{"type":"paragraph","data":{"text":"This is a welcome page."}}],"version":"2.15.1"}';

resolve(DataConverter::class)->init(json_decode($jsonContent));
```

Which should return 
```html<p>This is a welcome page.</p>```

**Comment by snake-py** [comment]
Hello Wotta, 

I tried it out now, had no time before sorry that it took me so long. I get when I supply this data:
```
{"time":1587722686439,"blocks":[{"type":"paragraph","data":{"text":"Der erste Post"}},{"type":"image","data":{"file":{"url":"http://tannzapfenland.local/storage/img/blog/20180103_204851-1587722680.jpg"},"caption":"Lecker","withBorder":false,"stretched":false,"withBackground":false}}],"version":"2.17.0"}
```
```
TypeError
Argument 1 passed to Motivo\EditorJsDataConverter\DataConverter::init() must be of the type string, object given, called in C:\xampp\htdocs\tannzapfenland\tannzapfenland\app\Http\Controllers\PostController.php on line 100
``` 

Not sure if it is my fault, I did it like you showed me, see code below:

```
   public function show($id)
    {
        $post = Post::find($id);
        print_r($post->text);

        $postHTML = resolve(DataConverter::class)->init(json_decode($post->text));

        return view('blog.show')->with('post', $post);
        
    }
```

**Comment by snake-py** [comment]
Also, when I remove the json decode it seems to work, but then i get:

**Comment by snake-py** [comment]
```
Motivo\EditorJsDataConverter\Exceptions\ConverterException
No converter registered for type `paragraph`
```

```
    public function show($id)
    {
        $post = Post::find($id);
        print_r($post->text);
        print_r(json_decode($post->text));
        print_r(gettype(json_decode($post->text)));

        $postHTML = resolve(DataConverter::class)->init($post->text);

        return view('blog.show')->with('post', $post);
        
    }
```

**Comment by wotta** [comment]
@snake-py do you happen to have a repo with the code?
That way I can take a look and try to fix it.

**Comment by snake-py** [comment]
@wotta I wrote last night a parser in js, so it is no urgent matter. Do you want to have the code anyway?

**Comment by wotta** [comment]
If you can put up a repo with problem i can help you out today. Not sure what time yet tho.

**Comment by snake-py** [comment]
No don't bother, I already made my own solution.
